const strings = {
    es: {
      title: "Jere.Dev",
      about: "Acerca de mí",
      skills: "Habilidades",
      projects: "Proyectos",
      experience: "Experiencia",
      contact: "Contacto",
      language: "ES",
      name: "Jeremias Fuentes",
      description: "Programador Full Stack",
      light: "Modo claro",
      dark: "Modo oscuro",
      mail: "jeremiasfuentes77@gmail.com",
      about: "Sobre mi",
      linkedin: "Linkedin",
      github: "Github",
      aboutme1: "Soy programador con título de técnico, tengo un buen desempeño y conocimiento en varias tecnologías (tales como Java, React, JavaScript, SQL, Docker, Blue Prism). Además, gracias a mi formación académica, poseo las herramientas adecuadas para adaptarme rápidamente a cualquier nueva tecnología que se precise.",
      aboutme2: "Actualmente tengo un puesto de Líder de Desarrollo RPA, en el que día a día coordino con mi equipo para crear software de calidad. Soy el referente técnico ante cualquier desafío que surja, encargándome del diseño de soluciones y planificación integral del desarrollo del proyecto.",
      job1: "Líder de Desarrollo RPA",
      time1: "Julio 2022 - Presente · 2 yr 10 m [Buenos Aires, Argentina] [Automatización,Desarrollo de Software]",
      job1point1: "Coordinación y planificación de diversas células de desarrollo mediante una metodología AGILE para entregar software de valor y calidad.",
      job1point2: "Comunicación con el equipo funcional y usuarios finales para comprender los requerimientos y llegar al resultado esperado",
      job1point3: "Encargarse del diseño de la solución y dar apoyo técnico al equipo en las tecnologías conocidas, e investigar/aprender las nuevas que necesite el proyecto.",
      job2: "Desarrollador RPA",
      time2: "Abril 2021 - Julio 2022 · 1 yr 4 m [Buenos Aires, Argentina] [Automatización,Desarrollo de Software]",
      job2point1: "Desarrollar autimatizaciones para importantes clientes con la herramienta Blue Prism.",
      job2point2: "Interacción con diversos aplicativos (SAP, Excel, DevOps) mediante scripts en lenguajes como Python, Visual Basic o C#.",
      job2point3: "Comunicar activamente con mi líder y equipo funcional las dudas y los problemas que surgían.",
      project1: "Página web hecha con React para mostrar mis proyectos, experiencia y poder contactarme.",
      project2: "Página web para consultorio odontologico que permite manejar pacientes, turnos y documentos unicos de la profesion.",
      project3: "Página que funciona como un foro de cursos de programacion hecha para aprender mas de .NET, ASP.NET y Entity-Framework.",
      project4: "Videojuego RPG de accion creado en Godot como proyecto final para la materia de desarrollo de videojuegos.",
      technology: "Tecnologias",
      contactme: "Contactame",
      nombre: "Tu Nombre",
      email: "Tu Email",
      message: "Tu Mensaje",
      sendmessagge: "Enviar Mensaje",
      successmessage: "Mensaje Enviado!",
      errormessage: "Error al enviar mensaje."
    },
    en: {
      title: "Jere.Dev",
      about: "About me",
      skills: "Skills",
      projects: "Projects",
      experience: "Experience",
      contact: "Contact",
      language: "EN",
      name: "Jeremias Fuentes",
      description: "Full Stack Developer",
      light: "Light Mode",
      dark: "Dark Mode",
      mail: "jeremiasfuentes77@gmail.com",
      linkedin:"Linkedin",
      github: "Github",
      aboutme1: "I'm a skilled programmer with a technical degree, showcasing proficiency in various technologies such as Java, React, JavaScript, SQL, Docker, and Blue Prism. My academic background equips me with the tools to swiftly adapt to new technologies as needed.",
      aboutme2: "Currently, I hold the position of RPA Development Leader, where I collaborate daily with my team to deliver high-quality software. Serving as the technical focal point, I address challenges, oversee solution design, and ensure comprehensive planning for project development.",
      job1: "RPA Technical Leader",
      time1: "July 2022 - Present · 2 yrs 11 m [Buenos Aires, Argentina] [Automation, Software Development]",
      job1point1: "Coordination and planning of various development teams using AGILE methodology to deliver valuable and quality software.",
      job1point2: "Communication with the functional team and end-users to understand requirements and achieve the expected results.",
      job1point3: "Overseeing solution design and providing technical support to the team in familiar technologies, as well as researching/learning new ones as needed for the project.",
      job2: "RPA Developer",
      time2: "April 2021 - July 2022 · 1 yr 4 m [Buenos Aires, Argentina] [Automation, Software Development]",
      job2point1: "Developed automations for major clients using the Blue Prism tool.",
      job2point2: "Interacted with various applications (SAP, Excel, DevOps) through scripts in languages such as Python, Visual Basic, or C#.",
      job2point3: "Actively communicated doubts and issues with my leader and functional team.",
      project1: "Website made with React to show my projects, experience and to contact me.",
      project2: "Website for dental office to manage patients, appointments and unique documents of the profession.",
      project3: "Website that works as a forum for programming courses made to learn more about .NET, ASP.NET and Entity-Framework.",
      project4: "Action RPG video game created in Godot as a final project for the video game development course.",
      technology: "Technologies",
      contactme: "Contact me",
      nombre: "Your Name",
      email: "Your Email",
      message: "Your Message",
      sendmessagge: "Send Message",
      successmessage: "Message Sent Successfully!",
      errormessage: "Error sending message."
    },
  };

  export default strings;